2021-05-24 17:41:32,932 - __main__ - INFO - Web app initialization
2021-05-24 17:41:32,961 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-05-24 17:41:32,962 - werkzeug - INFO -  * Running on http://172.23.181.209:5000/ (Press CTRL+C to quit)
2021-05-24 17:41:40,889 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 17:41:40] "POST /api/instagram/find HTTP/1.1" 200 -
2021-05-24 17:41:59,724 - client - ERROR - Exception on /api/login [POST]
Traceback (most recent call last):
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "client.py", line 57, in login
    return jsonify({'token': token})
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/json/__init__.py", line 348, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/json/__init__.py", line 129, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/json/__init__.py", line 56, in default
    return super().default(o)
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2021-05-24 17:41:59,890 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 17:41:59] "[35m[1mPOST /api/login HTTP/1.1[0m" 500 -
2021-05-24 17:42:51,185 - __main__ - INFO - Web app initialization
2021-05-24 17:42:51,216 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-05-24 17:42:51,217 - werkzeug - INFO -  * Running on http://172.23.181.209:5000/ (Press CTRL+C to quit)
2021-05-24 17:42:54,848 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 17:42:54] "POST /api/login HTTP/1.1" 200 -
2021-05-24 17:55:44,374 - core - INFO - Web app initialization
2021-05-24 17:56:13,184 - core - INFO - Web app initialization
2021-05-24 17:57:13,971 - core - INFO - Web app initialization
2021-05-24 17:57:14,208 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-05-24 17:57:14,208 - werkzeug - INFO -  * Running on http://172.23.181.209:5000/ (Press CTRL+C to quit)
2021-05-24 17:57:23,872 - core - ERROR - Exception on /api/instagram/find [POST]
Traceback (most recent call last):
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/d/Projects/userprofiles/backend/src/core/__init__.py", line 44, in decorated
    data = jwt.decode(token, application.config['SECRET_KEY'])
NameError: name 'application' is not defined
2021-05-24 17:57:23,898 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 17:57:23] "[35m[1mPOST /api/instagram/find HTTP/1.1[0m" 500 -
2021-05-24 17:59:48,317 - core - INFO - Web app initialization
2021-05-24 17:59:48,467 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-05-24 17:59:48,468 - werkzeug - INFO -  * Running on http://172.23.181.209:5000/ (Press CTRL+C to quit)
2021-05-24 17:59:54,532 - core - ERROR - Exception on /api/instagram/find [POST]
Traceback (most recent call last):
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/d/Projects/userprofiles/backend/src/core/__init__.py", line 50, in decorated
    return f(*args, **kwargs)
  File "/mnt/d/Projects/userprofiles/backend/src/instagram/routes/routes.py", line 7, in upload_data
    return make_response(jsonify({'success': True}), 200, {'ContentType': 'application/json'})
NameError: name 'make_response' is not defined
2021-05-24 17:59:54,556 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 17:59:54] "[35m[1mPOST /api/instagram/find HTTP/1.1[0m" 500 -
2021-05-24 18:00:39,791 - core - INFO - Web app initialization
2021-05-24 18:00:39,986 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-05-24 18:00:39,987 - werkzeug - INFO -  * Running on http://172.23.181.209:5000/ (Press CTRL+C to quit)
2021-05-24 18:00:45,776 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 18:00:45] "POST /api/instagram/find HTTP/1.1" 200 -
2021-05-24 18:02:13,890 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 18:02:13] "[33mGET / HTTP/1.1[0m" 404 -
2021-05-24 18:02:14,210 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 18:02:14] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2021-05-24 18:02:32,193 - core - ERROR - Exception on /api/login [POST]
Traceback (most recent call last):
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/ribek/.conda/envs/MultiEnv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/d/Projects/userprofiles/backend/src/core/routes.py", line 10, in login
    auth = request.authorization
NameError: name 'request' is not defined
2021-05-24 18:02:32,243 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 18:02:32] "[35m[1mPOST /api/login HTTP/1.1[0m" 500 -
2021-05-24 18:03:02,750 - core - INFO - Web app initialization
2021-05-24 18:03:02,939 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-05-24 18:03:02,940 - werkzeug - INFO -  * Running on http://172.23.181.209:5000/ (Press CTRL+C to quit)
2021-05-24 18:03:07,567 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 18:03:07] "POST /api/login HTTP/1.1" 200 -
2021-05-24 18:03:18,078 - werkzeug - INFO - 127.0.0.1 - - [24/May/2021 18:03:18] "POST /api/instagram/find HTTP/1.1" 200 -
